# -*- coding: utf-8 -*-
"""Python3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dc8U7n2hpSm8hGU5FTp7t5rLEhaP1LXS

# Dictionary
"""

d={}
type(d)

# key should be unique
d1={'key':"Nave"}

d1

# special case charecter cannot be used
d2={"Name":"Naveen","Email":'navee',"Number":12345}

d3={234:'sudh','@wer':34,True:23}

d3[234]

d3[1]

d3['@wer']

# overwrites last value
d2={"Name":"Naveen","Email":'navee',"Number":12345,'Name':"Nav"}

d2["Name"]

d5={"company":"pwskills","Course":["web dev","data science","DSA"]}

d5

d5['Course'][2]

d6={"Number":[2,3,4,5,6,34,56],"assignment":(1,2,3,4,5),"launch":{28,12,14},"class_time":{'webdev':8,"datascience":9}}

d6

d6["class_time"]["datascience"]

# adds a kry
d6['mentor']=['sudhanshu','krish']

d6

# deletes a key
del d6['Number']

d6

list(d6.keys())

list(d6.values())

list(d6.items())

d6.pop('assignment')

d6

"""# Conditional statements"""

#python follows indentation
#input function always gives output as string
marks=int(input('Enter your marks'))
if marks >=80 :
  print("You will be a part of a0 batch")
elif marks>=60 and  marks<80:
  print('You will be a part of a1 batch')
elif marks>=40 and marks<60:
  print('You will be a part of a2 batch')
else:
  print('You will be a part of a3 batch')

price=int(input("Enter the price"))
if price>1000:
  print("I will nor purchase")
else:
  print("I will purchase")

price=int(input("Enter the price"))
if price>1000:
  print("I will not purchase")
if price>5000:
  print("this is too much")
elif price<2000 :
  print("it's okay")

l=[1,2,3,4,5,66,7,8,9]

l[0]+1

l1=[]

l1.append(l[0]+1)

l1

for n in l:
  print(n)

l1=[]
for i in l:
  print(i+1)
  l1.append(i+1)
l1

l=['sudh','kumar','pwskills','course']

l2=[]
for i in l:
  print(i)
  l2.append(i.upper())

l2

l=[1,2,3,3,"sudh","nav",87.7]

l1_num=[]
l2_str=[]
for i in l:
  if type(i)==int or type(i)==float:
    l1_num.append(i)
  else:
    l2_str.append(i)

l1_num

l2_str

